Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "idouniS" do |server|
    server.vm.hostname = "idouniS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", path: "scripts/Server_setup.bash"
    server.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "2048"
      vb.cpus = 2
    end
  end
end
