Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "idouniS" do |server|
    server.vm.hostname = "idouniS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", path: "scripts/Server_setup.bash"
    server.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  config.vm.define "idouniSW" do |worker|
    worker.vm.hostname = "idouniSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provision "shell", path: "scripts/ServerWorker_setup.bash"
    worker.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = 1
    end
  end
end
